version: '3.7'
services:
  postgres:
    image: library/postgres:13
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=event-admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notification
    